### ISSUE TITLE
'USER STORY: Create User Account'

### ISSUE THREAD

**Issue by pieterkdevilliers** [pieterkdevilliers/priority-tracking#1]
As a **user** I can **sign up for an account** so that **I can start tracking my time**

## Acceptance Criteria:

- Acceptance Criteria 1: Sign-up for User Account
- Acceptance Criteria 2: Receive Login Details
- Acceptance Criteria 3: Log In with Account Details

## Tasks:
- [ ] Sign-up Form
- [ ] User Groups & Admin Permissions
- [ ] Login Form
- [ ] Main Account Page
